### ISSUE TITLE
DroidLane Issue

### ISSUE THREAD

**Issue by Detor** [Jintin/DroidLane#1]
I applied the droidlane v1.2.0 into android studio 1.5.1 and it does not work

**Comment by Jintin** [comment]
Hi, what message do you get?
This one, "please add data in .droidlane first, See https://github.com/Jintin/DroidLane for more information"?
Or the upload fail message?
Can you give me more information about your problem? 
Thank you for your feedback.

**Comment by Jintin** [comment]
Hi, do you have any update?

**Comment by Jintin** [comment]
If you have any further question, you can raise another issue.
Thank you for your feedback anyway.
