### ISSUE TITLE
Help, every time I try droidlane, this pops up:

### ISSUE THREAD

**Issue by Detor** [Jintin/DroidLane#2]
"please add data in .droidlane first, See https://github.com/Jintin/DroidLane for more information"

**Comment by Jintin** [comment]
Did you follow the setup step in README?
Please let me know if you have further problem.
Thank you. ^^

## Usage
- Go to Google Play **[Settings] -> [API access] -> [Create OAuth Client]** and keep your [CLIENT ID] and [CLIENT SECRET]
- Go to your project root dir create `.droidlane/[profile_name]/data.json` with content:
  
  ``` json
  {
  "client_id": "[CLIENT ID]",
  "package": "[PACKAGE NAME]",
  "apk": "[APK PATH]",
  "track": "['alpha', 'beta' or 'production'](optional)"
  }
  ```
- Run DroidLane command in **[Build] -> [Upload Apk]**
- Select track if not define in data.json
- Set [CLIENT SECRET] and encrypt with password
- OAuth permission accept in browser

After first-time setup, you only need click button and key-in password to upload apk.

**Comment by Jintin** [comment]
Do you have any update?

**Comment by Jintin** [comment]
Did you try again?

**Comment by Detor** [comment]
I haven't yet tried, but since it's the weekends I might be able to

**Comment by Jintin** [comment]
Tell me if you have any problem. ^^

**Comment by Jintin** [comment]
Do you have any question?
We also add the Play Store listing function.
You can try it too.

**Comment by Detor** [comment]
Not right now, my computer's hard drive failed, I now have to fix it :(

**Comment by Jintin** [comment]
Have you tried? ^^

**Comment by Detor** [comment]
Yes it now works, thank you and sorry for the long wait :)

**Comment by Jintin** [comment]
Thank you for help me close the issue.
It would be great if you can give us a star! 
^^
